@startuml
title
  <i>Standard icons</u> from [Open Iconic](https://useiconic.com/open/)
end title

scale max 1024 width

' Removing color and border from cards
skinparam cardBorderColor none
skinparam cardBackgroundColor none
skinparam cardShadowing false

card "<size:42><&account-login></size>\naccount-login"
card "<size:42><&account-logout></size>\naccount-logout"
card "<size:42><&action-redo></size>\naction-redo"
card "<size:42><&action-undo></size>\naction-undo"
card "<size:42><&align-center></size>\nalign-center"
card "<size:42><&align-left></size>\nalign-left"
card "<size:42><&align-right></size>\nalign-right"

card "<size:42><&aperture></size>\naperture"
card "<size:42><&arrow-bottom></size>\narrow-bottom"
card "<size:42><&arrow-circle-bottom></size>\narrow-circle-bottom"
card "<size:42><&arrow-circle-left></size>\narrow-circle-left"
card "<size:42><&arrow-circle-right></size>\narrow-circle-right"
card "<size:42><&arrow-circle-top></size>\narrow-circle-top"
card "<size:42><&arrow-left></size>\narrow-left"
card "<size:42><&arrow-right></size>\narrow-right"
card "<size:42><&arrow-thick-bottom></size>\narrow-thick-bottom"
card "<size:42><&arrow-thick-left></size>\narrow-thick-left"
card "<size:42><&arrow-thick-right></size>\narrow-thick-right"
card "<size:42><&arrow-thick-top></size>\narrow-thick-top"
card "<size:42><&arrow-top></size>\narrow-top"
card "<size:42><&audio></size>\naudio"
card "<size:42><&audio-spectrum></size>\naudio-spectrum"
card "<size:42><&badge></size>\nbadge"
card "<size:42><&ban></size>\nban"
card "<size:42><&bar-chart></size>\nbar-chart"
card "<size:42><&basket></size>\nbasket"
card "<size:42><&battery-empty></size>\nbattery-empty"
card "<size:42><&battery-full></size>\nbattery-full"
card "<size:42><&beaker></size>\nbeaker"
card "<size:42><&bell></size>\nbell"
card "<size:42><&bluetooth></size>\nbluetooth"
card "<size:42><&bold></size>\nbold"
card "<size:42><&bolt></size>\nbolt"
card "<size:42><&book></size>\nbook"
card "<size:42><&bookmark></size>\nbookmark"
card "<size:42><&box></size>\nbox"
card "<size:42><&briefcase></size>\nbriefcase"
card "<size:42><&british-pound></size>\nbritish-pound"
card "<size:42><&browser></size>\nbrowser"
card "<size:42><&brush></size>\nbrush"
card "<size:42><&bug></size>\nbug"
card "<size:42><&bullhorn></size>\nbullhorn"
card "<size:42><&calculator></size>\ncalculator"
card "<size:42><&calendar></size>\ncalendar"
card "<size:42><&camera-slr></size>\ncamera-slr"
card "<size:42><&caret-bottom></size>\ncaret-bottom"
card "<size:42><&caret-left></size>\ncaret-left"
card "<size:42><&caret-right></size>\ncaret-right"
card "<size:42><&caret-top></size>\ncaret-top"
card "<size:42><&cart></size>\ncart"
card "<size:42><&chat></size>\nchat"
card "<size:42><&check></size>\ncheck"
card "<size:42><&chevron-bottom></size>\nchevron-bottom"
card "<size:42><&chevron-left></size>\nchevron-left"
card "<size:42><&chevron-right></size>\nchevron-right"
card "<size:42><&chevron-top></size>\nchevron-top"
card "<size:42><&circle-check></size>\ncircle-check"
card "<size:42><&circle-x></size>\ncircle-x"
card "<size:42><&clipboard></size>\nclipboard"
card "<size:42><&clock></size>\nclock"
card "<size:42><&cloud></size>\ncloud"
card "<size:42><&cloud-download></size>\ncloud-download"
card "<size:42><&cloud-upload></size>\ncloud-upload"
card "<size:42><&cloudy></size>\ncloudy"
card "<size:42><&code></size>\ncode"
card "<size:42><&cog></size>\ncog"
card "<size:42><&collapse-down></size>\ncollapse-down"
card "<size:42><&collapse-left></size>\ncollapse-left"
card "<size:42><&collapse-right></size>\ncollapse-right"
card "<size:42><&collapse-up></size>\ncollapse-up"
card "<size:42><&command></size>\ncommand"
card "<size:42><&comment-square></size>\ncomment-square"
card "<size:42><&compass></size>\ncompass"
card "<size:42><&contrast></size>\ncontrast"
card "<size:42><&copywriting></size>\ncopywriting"
card "<size:42><&credit-card></size>\ncredit-card"
card "<size:42><&crop></size>\ncrop"
card "<size:42><&dashboard></size>\ndashboard"
card "<size:42><&data-transfer-download></size>\ndata-transfer-download"
card "<size:42><&data-transfer-upload></size>\ndata-transfer-upload"
card "<size:42><&delete></size>\ndelete"
card "<size:42><&dial></size>\ndial"
card "<size:42><&document></size>\ndocument"
card "<size:42><&dollar></size>\ndollar"
card "<size:42><&double-quote-sans-left></size>\ndouble-quote-sans-left"
card "<size:42><&double-quote-sans-right></size>\ndouble-quote-sans-right"
card "<size:42><&double-quote-serif-left></size>\ndouble-quote-serif-left"
card "<size:42><&double-quote-serif-right></size>\ndouble-quote-serif-right"
card "<size:42><&droplet></size>\ndroplet"
card "<size:42><&eject></size>\neject"
card "<size:42><&elevator></size>\nelevator"
card "<size:42><&ellipses></size>\nellipses"
card "<size:42><&envelope-closed></size>\nenvelope-closed"
card "<size:42><&envelope-open></size>\nenvelope-open"
card "<size:42><&euro></size>\neuro"
card "<size:42><&excerpt></size>\nexcerpt"
card "<size:42><&expand-down></size>\nexpand-down"
card "<size:42><&expand-left></size>\nexpand-left"
card "<size:42><&expand-right></size>\nexpand-right"
card "<size:42><&expand-up></size>\nexpand-up"
card "<size:42><&external-link></size>\nexternal-link"
card "<size:42><&eye></size>\neye"
card "<size:42><&eyedropper></size>\neyedropper"
card "<size:42><&file></size>\nfile"
card "<size:42><&fire></size>\nfire"
card "<size:42><&flag></size>\nflag"
card "<size:42><&flash></size>\nflash"
card "<size:42><&folder></size>\nfolder"
card "<size:42><&fork></size>\nfork"
card "<size:42><&fullscreen-enter></size>\nfullscreen-enter"
card "<size:42><&fullscreen-exit></size>\nfullscreen-exit"
card "<size:42><&globe></size>\nglobe"
card "<size:42><&graph></size>\ngraph"
card "<size:42><&grid-four-up></size>\ngrid-four-up"
card "<size:42><&grid-three-up></size>\ngrid-three-up"
card "<size:42><&grid-two-up></size>\ngrid-two-up"
card "<size:42><&hard-drive></size>\nhard-drive"
card "<size:42><&header></size>\nheader"
card "<size:42><&headphones></size>\nheadphones"
card "<size:42><&heart></size>\nheart"
card "<size:42><&home></size>\nhome"
card "<size:42><&image></size>\nimage"
card "<size:42><&inbox></size>\ninbox"
card "<size:42><&infinity></size>\ninfinity"
card "<size:42><&info></size>\ninfo"
card "<size:42><&italic></size>\nitalic"
card "<size:42><&justify-center></size>\njustify-center"
card "<size:42><&justify-left></size>\njustify-left"
card "<size:42><&justify-right></size>\njustify-right"
card "<size:42><&key></size>\nkey"
card "<size:42><&laptop></size>\nlaptop"
card "<size:42><&layers></size>\nlayers"
card "<size:42><&lightbulb></size>\nlightbulb"
card "<size:42><&link-broken></size>\nlink-broken"
card "<size:42><&link-intact></size>\nlink-intact"
card "<size:42><&list></size>\nlist"
card "<size:42><&list-rich></size>\nlist-rich"
card "<size:42><&location></size>\nlocation"
card "<size:42><&lock-locked></size>\nlock-locked"
card "<size:42><&lock-unlocked></size>\nlock-unlocked"
card "<size:42><&loop></size>\nloop"
card "<size:42><&loop-circular></size>\nloop-circular"
card "<size:42><&loop-square></size>\nloop-square"
card "<size:42><&magnifying-glass></size>\nmagnifying-glass"
card "<size:42><&map></size>\nmap"
card "<size:42><&map-marker></size>\nmap-marker"
card "<size:42><&media-pause></size>\nmedia-pause"
card "<size:42><&media-play></size>\nmedia-play"
card "<size:42><&media-record></size>\nmedia-record"
card "<size:42><&media-skip-backward></size>\nmedia-skip-backward"
card "<size:42><&media-skip-forward></size>\nmedia-skip-forward"
card "<size:42><&media-step-backward></size>\nmedia-step-backward"
card "<size:42><&media-step-forward></size>\nmedia-step-forward"
card "<size:42><&media-stop></size>\nmedia-stop"
card "<size:42><&medical-cross></size>\nmedical-cross"
card "<size:42><&menu></size>\nmenu"
card "<size:42><&microphone></size>\nmicrophone"
card "<size:42><&minus></size>\nminus"
card "<size:42><&monitor></size>\nmonitor"
card "<size:42><&moon></size>\nmoon"
card "<size:42><&move></size>\nmove"
card "<size:42><&musical-note></size>\nmusical-note"
card "<size:42><&paperclip></size>\npaperclip"
card "<size:42><&pencil></size>\npencil"
card "<size:42><&people></size>\npeople"
card "<size:42><&person></size>\nperson"
card "<size:42><&phone></size>\nphone"
card "<size:42><&pie-chart></size>\npie-chart"
card "<size:42><&pin></size>\npin"
card "<size:42><&play-circle></size>\nplay-circle"
card "<size:42><&plus></size>\nplus"
card "<size:42><&power-standby></size>\npower-standby"
card "<size:42><&print></size>\nprint"
card "<size:42><&project></size>\nproject"
card "<size:42><&pulse></size>\npulse"
card "<size:42><&puzzle-piece></size>\npuzzle-piece"
card "<size:42><&question-mark></size>\nquestion-mark"
card "<size:42><&rain></size>\nrain"
card "<size:42><&random></size>\nrandom"
card "<size:42><&reload></size>\nreload"
card "<size:42><&resize-both></size>\nresize-both"
card "<size:42><&resize-height></size>\nresize-height"
card "<size:42><&resize-width></size>\nresize-width"
card "<size:42><&rss></size>\nrss"
card "<size:42><&rss-alt></size>\nrss-alt"
card "<size:42><&script></size>\nscript"
card "<size:42><&share></size>\nshare"
card "<size:42><&share-boxed></size>\nshare-boxed"
card "<size:42><&shield></size>\nshield"
card "<size:42><&signal></size>\nsignal"
card "<size:42><&signpost></size>\nsignpost"
card "<size:42><&sort-ascending></size>\nsort-ascending"
card "<size:42><&sort-descending></size>\nsort-descending"
card "<size:42><&spreadsheet></size>\nspreadsheet"
card "<size:42><&star></size>\nstar"
card "<size:42><&sun></size>\nsun"
card "<size:42><&tablet></size>\ntablet"
card "<size:42><&tag></size>\ntag"
card "<size:42><&tags></size>\ntags"
card "<size:42><&target></size>\ntarget"
card "<size:42><&task></size>\ntask"
card "<size:42><&terminal></size>\nterminal"
card "<size:42><&text></size>\ntext"
card "<size:42><&thumb-down></size>\nthumb-down"
card "<size:42><&thumb-up></size>\nthumb-up"
card "<size:42><&timer></size>\ntimer"
card "<size:42><&transfer></size>\ntransfer"
card "<size:42><&trash></size>\ntrash"
card "<size:42><&underline></size>\nunderline"
card "<size:42><&vertical-align-bottom></size>\nvertical-align-bottom"
card "<size:42><&vertical-align-center></size>\nvertical-align-center"
card "<size:42><&vertical-align-top></size>\nvertical-align-top"
card "<size:42><&video></size>\nvideo"
card "<size:42><&volume-high></size>\nvolume-high"
card "<size:42><&volume-low></size>\nvolume-low"
card "<size:42><&volume-off></size>\nvolume-off"
card "<size:42><&warning></size>\nwarning"
card "<size:42><&wifi></size>\nwifi"
card "<size:42><&wrench></size>\nwrench"
card "<size:42><&x></size>\nx"
card "<size:42><&yen></size>\nyen"
card "<size:42><&zoom-in></size>\nzoom-in"
card "<size:42><&zoom-out></size>\nzoom-out"
@enduml
